  export const videos = [
    {
      id: 1,
      title: "Amazing Nature Documentary",
      channel: "Nature Explorer",
      views: "2.3M views",
      time: "3 days ago",
      thumbnail: "/placeholder.svg?height=200&width=350",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 2,
      title: "Cooking Masterclass: Italian Pasta",
      channel: "Chef's Kitchen",
      views: "856K views",
      time: "1 week ago",
      thumbnail: "/placeholder.svg?height=200&width=350",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 3,
      title: "Tech Review: Latest Smartphone",
      channel: "Tech Guru",
      views: "1.2M views",
      time: "2 days ago",
      thumbnail: "/placeholder.svg?height=200&width=350",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 4,
      title: "Travel Vlog: Tokyo Adventure",
      channel: "Wanderlust",
      views: "445K views",
      time: "5 days ago",
      thumbnail: "/placeholder.svg?height=200&width=350",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 5,
      title: "Music Production Tutorial",
      channel: "Beat Maker",
      views: "678K views",
      time: "1 day ago",
      thumbnail: "/placeholder.svg?height=200&width=350",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    {
      id: 6,
      title: "Fitness Workout: Full Body",
      channel: "Fit Life",
      views: "923K views",
      time: "4 days ago",
      thumbnail: "/placeholder.svg?height=200&width=350",
      avatar: "/placeholder.svg?height=40&width=40",
    },
  ]